In [82]:
# import dependancies
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np

In [83]:
#pull in google trend data 
google_trend_damage_df = pd.read_csv("C:/Users/OI/Desktop/g_trend.csv")
gt_coral_df = pd.read_csv("C:/Users/OI/Desktop/coral.csv")
gt_reef_df = pd.read_csv("C:/Users/OI/Desktop/reef.csv")
gt_coralreef_df = pd.read_csv("C:/Users/OI/Desktop/coral_reef.csv")
gt_reefdiving_df = pd.read_csv("C:/Users/OI/Desktop/reef_diving.csv")
gt_greatbarrier_df = pd.read_csv("C:/Users/OI/Desktop/great_barrier.csv")
gt_reef_scuba_df = pd.read_csv("C:/Users/OI/Desktop/reef_scuba.csv")

gt_coral_df.head(1)

     Month  coral: (Worldwide)
0  2004-01                  90

In [84]:
google_trend_all_df = pd.merge(google_trend_damage_df, gt_coral_df, on='Month')
google_trend_all_df = pd.merge(google_trend_all_df, gt_reef_df, on='Month')
google_trend_all_df = pd.merge(google_trend_all_df, gt_coralreef_df, on='Month')
google_trend_all_df = pd.merge(google_trend_all_df, gt_reefdiving_df, on='Month')
google_trend_all_df = pd.merge(google_trend_all_df, gt_greatbarrier_df, on='Month')
google_trend_all_df = pd.merge(google_trend_all_df, gt_reef_scuba_df, on='Month')


google_trend_all_df.head(100)

,Month,Reef damage,Coral reef Damaged,Coral Bleaching,Great Barrier Reef Damage,Coral Disease,Great Barrier Reef Oil Spill,Climate Change,Coral and El Nino,coral: (Worldwide),reef: (Worldwide),coral reef: (Worldwide),reef diving,great barrier reef,reef scuba
0,2004-01,18,0,82,81,23,0,24,9,90,89,90,100,48,100
1,2004-02,9,0,63,40,13,0,35,0,98,100,95,49,68,61
2,2004-03,28,11,56,0,17,0,32,11,98,98,97,76,86,82
3,2004-04,17,9,74,38,9,0,26,0,99,91,100,54,62,96
4,2004-05,30,0,94,100,23,12,28,0,99,95,100,71,83,87
5,2004-06,8,0,53,0,19,0,21,0,91,84,68,53,60,73
6,2004-07,0,0,24,0,16,0,19,0,84,80,56,73,39,91
7,2004-08,11,0,66,32,11,0,18,0,93,83,60,61,56,58
8,2004-09,37,0,40,0,20,0,23,0,83,76,75,63,50,61
9,2004-10,10,7,79,30,17,11,26,0,83,73,76,61,57,71
10,2004-11,0,0,65,0,31,0,31,0,82,69,78,69,56,67
11,2004-12,13,0,64,0,22,0,27,6,78,65,64,58,35,77
12,2005-01,20,0,56,0,25,0,30,0,87,82,78,50,32,51
13,2005-02,9,6,68,26,18,0,29,0,94,96,80,68,49,47
14,2005-03,32,0,59,87,12,0,29,5,93,91,78,58,61,72
15,2005-04,22,5,74,25,14,0,28,0,94,84,78,65,53,47
16,2005-05,7,0,66,22,22,0,25,5,95,86,83,68,67,77
17,2005-06,5,0,41,22,12,0,25,0,88,83,56,53,48,65
18,2005-07,28,0,33,22,10,0,23,0,85,80,50,54,33,54
19,2005-08,19,0,38,32,17,0,20,0,87,78,53,51,45,50
20,2005-09,15,0,48,29,11,0,26,9,80,67,61,44,42,74
21,2005-10,27,0,67,18,14,0,30,0,86,71,72,34,43,52
22,2005-11,22,4,77,18,8,6,34,0,80,67,66,47,41,57
23,2005-12,4,0,42,18,10,0,30,0,73,60,50,38,25,54
24,2006-01,14,4,55,16,11,6,27,0,85,72,63,48,28,69
25,2006-02,7,4,82,16,13,0,30,4,85,74,67,55,39,71
26,2006-03,12,0,74,14,22,5,36,3,91,71,68,44,50,51
27,2006-04,15,3,84,0,13,0,30,0,91,72,65,42,36,35
28,2006-05,12,6,89,14,15,5,33,0,87,74,70,33,44,48
29,2006-06,13,6,36,14,6,0,29,0,80,72,48,41,32,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2009-11,6,1,63,10,9,1,84,1,73,45,42,29,24,35
71,2009-12,4,0,32,4,4,0,100,0,68,42,34,20,15,30
72,2010-01,3,2,27,7,7,0,57,1,78,50,40,28,18,42
73,2010-02,6,3,34,10,6,1,59,1,80,50,45,25,22,30
74,2010-03,6,1,47,8,7,1,56,1,81,52,45,25,28,34
75,2010-04,9,2,45,21,8,100,52,2,83,56,48,28,42,28
76,2010-05,6,1,55,16,6,47,47,1,81,53,47,28,30,32
77,2010-06,4,1,34,5,8,19,35,1,77,50,37,27,21,28
78,2010-07,2,1,22,7,6,18,31,1,79,51,35,28,16,33
79,2010-08,3,1,36,10,6,7,33,0,78,50,38,31,20,30
80,2010-09,4,0,36,0,5,6,37,0,72,43,37,22,21,28
81,2010-10,5,2,53,0,6,3,41,1,72,42,37,25,22,26
82,2010-11,2,3,43,6,9,3,44,1,77,47,35,23,22,31
83,2010-12,2,0,28,0,6,2,36,1,73,42,29,17,13,24
84,2011-01,4,1,29,4,7,1,36,1,80,48,34,27,18,28
85,2011-02,6,2,33,7,5,1,39,1,80,49,38,20,20,25
86,2011-03,7,2,48,6,8,4,42,1,82,48,40,23,23,27
87,2011-04,6,1,38,8,9,0,36,1,88,46,38,24,19,29
88,2011-05,6,1,44,8,6,3,39,1,84,48,41,24,25,30
89,2011-06,3,1,19,3,6,4,32,2,83,51,34,26,19,30
90,2011-07,3,1,17,3,3,2,28,0,82,47,31,22,14,31
91,2011-08,4,1,17,5,4,2,27,1,83,47,34,24,18,25
92,2011-09,3,1,27,5,6,2,33,1,79,43,35,20,19,27
93,2011-10,5,2,35,10,5,1,35,1,76,42,37,24,19,28
94,2011-11,4,2,41,6,5,1,41,1,75,42,34,19,21,22
95,2011-12,2,1,23,0,8,2,32,1,75,41,32,19,14,22
96,2012-01,3,<1,25,7,7,1,30,<1,81,47,37,25,22,29
97,2012-02,2,1,37,2,10,2,35,1,81,46,38,20,20,29
98,2012-03,5,<1,39,7,6,2,36,1,84,46,39,25,25,26
99,2012-04,3,1,37,7,8,1,33,1,86,46,39,20,18,29

In [85]:
google_trend_all_df = google_trend_all_df.rename(columns={"coral: (Worldwide)": "coral","reef: (Worldwide)":"reef", "coral reef: (Worldwide)":"coral reef" })

google_trend_all_df.head()

,Month,Reef damage,Coral reef Damaged,Coral Bleaching,Great Barrier Reef Damage,Coral Disease,Great Barrier Reef Oil Spill,Climate Change,Coral and El Nino,coral,reef,coral reef,reef diving,great barrier reef,reef scuba
0,2004-01,18,0,82,81,23,0,24,9,90,89,90,100,48,100
1,2004-02,9,0,63,40,13,0,35,0,98,100,95,49,68,61
2,2004-03,28,11,56,0,17,0,32,11,98,98,97,76,86,82
3,2004-04,17,9,74,38,9,0,26,0,99,91,100,54,62,96
4,2004-05,30,0,94,100,23,12,28,0,99,95,100,71,83,87

In [86]:
google_trend_all_df["average"] = google_trend_all_df.mean(axis=1)

google_trend_all_df = google_trend_all_df.set_index("Month")

google_trend_all_df.head(100)

,Reef damage,Coral reef Damaged,Coral Bleaching,Great Barrier Reef Damage,Coral Disease,Great Barrier Reef Oil Spill,Climate Change,Coral and El Nino,coral,reef,coral reef,reef diving,great barrier reef,reef scuba,average
Month,,,,,,,,,,,,,,,
2004-01,18,0,82,81,23,0,24,9,90,89,90,100,48,100,67.727273
2004-02,9,0,63,40,13,0,35,0,98,100,95,49,68,61,57.363636
2004-03,28,11,56,0,17,0,32,11,98,98,97,76,86,82,60.909091
2004-04,17,9,74,38,9,0,26,0,99,91,100,54,62,96,60.545455
2004-05,30,0,94,100,23,12,28,0,99,95,100,71,83,87,73.636364
2004-06,8,0,53,0,19,0,21,0,91,84,68,53,60,73,48.181818
2004-07,0,0,24,0,16,0,19,0,84,80,56,73,39,91,43.818182
2004-08,11,0,66,32,11,0,18,0,93,83,60,61,56,58,49.909091
2004-09,37,0,40,0,20,0,23,0,83,76,75,63,50,61,48.000000
2004-10,10,7,79,30,17,11,26,0,83,73,76,61,57,71,53.000000
2004-11,0,0,65,0,31,0,31,0,82,69,78,69,56,67,49.818182
2004-12,13,0,64,0,22,0,27,6,78,65,64,58,35,77,45.727273
2005-01,20,0,56,0,25,0,30,0,87,82,78,50,32,51,46.454545
2005-02,9,6,68,26,18,0,29,0,94,96,80,68,49,47,53.090909
2005-03,32,0,59,87,12,0,29,5,93,91,78,58,61,72,61.090909
2005-04,22,5,74,25,14,0,28,0,94,84,78,65,53,47,53.090909
2005-05,7,0,66,22,22,0,25,5,95,86,83,68,67,77,56.181818
2005-06,5,0,41,22,12,0,25,0,88,83,56,53,48,65,45.272727
2005-07,28,0,33,22,10,0,23,0,85,80,50,54,33,54,42.909091
2005-08,19,0,38,32,17,0,20,0,87,78,53,51,45,50,44.545455
2005-09,15,0,48,29,11,0,26,9,80,67,61,44,42,74,45.181818
2005-10,27,0,67,18,14,0,30,0,86,71,72,34,43,52,46.727273
2005-11,22,4,77,18,8,6,34,0,80,67,66,47,41,57,47.000000
2005-12,4,0,42,18,10,0,30,0,73,60,50,38,25,54,36.727273
2006-01,14,4,55,16,11,6,27,0,85,72,63,48,28,69,44.363636
2006-02,7,4,82,16,13,0,30,4,85,74,67,55,39,71,49.000000
2006-03,12,0,74,14,22,5,36,3,91,71,68,44,50,51,48.454545
2006-04,15,3,84,0,13,0,30,0,91,72,65,42,36,35,43.909091
2006-05,12,6,89,14,15,5,33,0,87,74,70,33,44,48,47.181818
2006-06,13,6,36,14,6,0,29,0,80,72,48,41,32,43,37.636364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-11,6,1,63,10,9,1,84,1,73,45,42,29,24,35,38.181818
2009-12,4,0,32,4,4,0,100,0,68,42,34,20,15,30,32.090909
2010-01,3,2,27,7,7,0,57,1,78,50,40,28,18,42,32.454545
2010-02,6,3,34,10,6,1,59,1,80,50,45,25,22,30,33.363636
2010-03,6,1,47,8,7,1,56,1,81,52,45,25,28,34,35.363636
2010-04,9,2,45,21,8,100,52,2,83,56,48,28,42,28,38.181818
2010-05,6,1,55,16,6,47,47,1,81,53,47,28,30,32,36.454545
2010-06,4,1,34,5,8,19,35,1,77,50,37,27,21,28,29.636364
2010-07,2,1,22,7,6,18,31,1,79,51,35,28,16,33,28.181818
2010-08,3,1,36,10,6,7,33,0,78,50,38,31,20,30,30.454545
2010-09,4,0,36,0,5,6,37,0,72,43,37,22,21,28,27.727273
2010-10,5,2,53,0,6,3,41,1,72,42,37,25,22,26,29.909091
2010-11,2,3,43,6,9,3,44,1,77,47,35,23,22,31,30.818182
2010-12,2,0,28,0,6,2,36,1,73,42,29,17,13,24,24.545455
2011-01,4,1,29,4,7,1,36,1,80,48,34,27,18,28,28.636364
2011-02,6,2,33,7,5,1,39,1,80,49,38,20,20,25,29.272727
2011-03,7,2,48,6,8,4,42,1,82,48,40,23,23,27,32.181818
2011-04,6,1,38,8,9,0,36,1,88,46,38,24,19,29,31.000000
2011-05,6,1,44,8,6,3,39,1,84,48,41,24,25,30,32.272727
2011-06,3,1,19,3,6,4,32,2,83,51,34,26,19,30,27.818182
2011-07,3,1,17,3,3,2,28,0,82,47,31,22,14,31,25.545455
2011-08,4,1,17,5,4,2,27,1,83,47,34,24,18,25,26.181818
2011-09,3,1,27,5,6,2,33,1,79,43,35,20,19,27,27.000000
2011-10,5,2,35,10,5,1,35,1,76,42,37,24,19,28,28.727273
2011-11,4,2,41,6,5,1,41,1,75,42,34,19,21,22,28.181818
2011-12,2,1,23,0,8,2,32,1,75,41,32,19,14,22,24.363636
2012-01,3,<1,25,7,7,1,30,<1,81,47,37,25,22,29,28.454545
2012-02,2,1,37,2,10,2,35,1,81,46,38,20,20,29,29.090909
2012-03,5,<1,39,7,6,2,36,1,84,46,39,25,25,26,30.727273
2012-04,3,1,37,7,8,1,33,1,86,46,39,20,18,29,29.636364

In [87]:
# google_trend_piv = google_trend_all_df.pivot_table

google_df_transpose = google_trend_all_df.T

google_df_transpose.head()


# plot = plt.plot()

Month,2004-01,2004-02,2004-03,2004-04,2004-05,2004-06,2004-07,2004-08,2004-09,2004-10,...,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10
Reef damage,18,9,28,17,30,8,0,11,37,10,...,5,5,5,6,7,5,3,4,4,2
Coral reef Damaged,0,0,11,9,0,0,0,0,0,7,...,1,1,1,<1,2,<1,<1,<1,1,1
Coral Bleaching,82,63,56,74,94,53,24,66,40,79,...,53,61,70,86,87,44,29,45,63,73
Great Barrier Reef Damage,81,40,0,38,100,0,0,32,0,30,...,3,5,6,7,4,11,2,9,10,6
Coral Disease,23,13,17,9,23,19,16,11,20,17,...,4,5,8,9,7,4,5,5,7,6

In [93]:
google_df_transpose.dtypes

Month
2004-01    object
2004-02    object
2004-03    object
2004-04    object
2004-05    object
2004-06    object
2004-07    object
2004-08    object
2004-09    object
2004-10    object
2004-11    object
2004-12    object
2005-01    object
2005-02    object
2005-03    object
2005-04    object
2005-05    object
2005-06    object
2005-07    object
2005-08    object
2005-09    object
2005-10    object
2005-11    object
2005-12    object
2006-01    object
2006-02    object
2006-03    object
2006-04    object
2006-05    object
2006-06    object
            ...
2016-05    object
2016-06    object
2016-07    object
2016-08    object
2016-09    object
2016-10    object
2016-11    object
2016-12    object
2017-01    object
2017-02    object
2017-03    object
2017-04    object
2017-05    object
2017-06    object
2017-07    object
2017-08    object
2017-09    object
2017-10    object
2017-11    object
2017-12    object
2018-01    object
2018-02    object
2018-03    object
2018-04    object
2018-05    object
2018-06    object
2018-07    object
2018-08    object
2018-09    object
2018-10    object
Length: 178, dtype: object